server:
  port: 80

spring:
  application:
    name: assign-service


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/team2?useSSL=false&useUnicode=false&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#spring.jpa.properties.hibernate.format_sql=true